INSERT INTO years (year, year_start) VALUES (2017, 1504569600);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 1);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 2);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 3);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 4);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 5);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 6);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 7);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 8);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 9);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 10);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 11);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 12);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 13);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 14);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 15);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 16);
INSERT INTO weeks (year_id, week) VALUES ((SELECT years.id FROM years WHERE year = 2017), 17);
