\c nfl_app

DELETE FROM statistics;
DELETE FROM picks;
DELETE FROM games;
DELETE FROM weeks;
DELETE FROM years;
DELETE FROM teams;
DELETE FROM pvs;
DELETE FROM users;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pvs CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS years CASCADE;
DROP TABLE IF EXISTS weeks CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS picks CASCADE; 
DROP TABLE IF EXISTS statistics CASCADE;
